introducing basic OneLogin integration in to Track My Case UI prototype; (#24)
* feat: introducing basic OneLogin integration in to Track My Case UI prototype;
* feat: introducing basic OneLogin header;

---------

Co-authored-by: Dmitri Algazin <Dmitri.Algazin1@justice.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,1 +1,9 @@
-npx --no -- commitlint --edit "$1"
+#!/bin/sh
+FILE="${1:-.git/COMMIT_EDITMSG}"
+
+if [ ! -f "$FILE" ]; then
+  echo "❌ commitlint: file '$FILE' not found"
+  exit 1
+fi
+
+npx --no -- commitlint --edit "$FILE"
